// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package userstore

import (
	"context"

	"github.com/MWT-proger/go-sqlc-clean-architecture-example/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (models.AuthUser, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetUser(ctx context.Context, id uuid.UUID) (models.AuthUser, error)
	ListUsers(ctx context.Context) ([]models.AuthUser, error)
}

var _ Querier = (*Queries)(nil)
